#!/usr/bin/env python3

import sys
import re
import subprocess
import shlex
import argparse
import locale
import pprint
import itertools


class VarDict(dict):

     def __init__(self, *arg, **kw):
        super(VarDict, self).__init__(*arg, **kw)

     def is_regex(self, k):
         return isinstance(self.get(k), str)

     def is_range(self, k):
         return isinstance(self.get(k), tuple)

     def is_enum(self, k):
         return isinstance(self.get(k), list)


def get_test_strings():
    whitespace = [' ', '\t', '\n']
    punctuation = ['.', '_', '-', '&']
    digits = ['1']
    symbols = whitespace + punctuation + digits
    numbers = [1, 1.1, 10, 100, 1000, 10**10, 10**50]
    lengths = [1, 4, 8, 16, 32, 2048]
    # Empty string or with whitespace only
    test_strings = whitespace
    # With whitespace, punctuation or a digit in the beginning
    test_strings += [s + "teststring" for s in symbols]
    # With whitespace, punctuation or a digit in the middle
    test_strings += ["test" + s + "string" for s in symbols]
    # Numbers
    test_strings += itertools.chain.from_iterable(
        (i, -i) for i in numbers)
    test_strings.append(0)
    # Lowercase/uppercase combinations
    test_strings += ["teststring", "Teststring", "TESTSTRING"]
    # Non-printable characters
    test_strings.append(r'test\0string')
    # Different lengths
    test_strings += itertools.chain.from_iterable(
        ("x" * (n - 1), "x" * n) for n in lengths)
    return test_strings


def shell_quote(argument):
    return "'{}'".format(argument.replace("'", r"'\''"))


def run_command(cmd, ns, should_succeed):
    cmd = re.sub(' +', ' ', cmd).strip()
    debug_str = "Running " + cmd
    if should_succeed:
        debug_str += " (should succeed)"
    if ns.verbose:
        print (debug_str)
    process = subprocess.Popen(shlex.split(cmd),
                               stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE)
    outdata, errdata = process.communicate()
    encoding = locale.getdefaultlocale()[1]
    test_failed = False
    if should_succeed and process.returncode != 0:
        test_failed = True
    if not should_succeed:
        if process.returncode == 0:
            test_failed = True
        if ns.error_string:
            for es in ns.error_string:
                 if es in errdata.decode(encoding):
                     break
            else:
                test_failed = True
    if test_failed:
        if not ns.quiet:
            if not ns.verbose:
                print (debug_str)
            sys.stderr.write("    Failed.\n")
        sys.exit(1)


def expand_regex(option, var_name, line, var_dict, ns, expanded,
                 should_succeed):
    found_match = False
    for ts in ns.test_string:
        if isinstance(ts, (int, float)):
            l2 = line.replace(var_name, str(ts), 1)
        else:
            l2 = line.replace(var_name, shell_quote(ts), 1)
        regex = var_dict[var_name[1:]]
        if re.search(regex, str(ts)):
            found_match = True
            expand_cmd(l2, var_dict, ns, expanded, should_succeed)
            if option in expanded:
                break
        elif should_succeed and option not in expanded:
            expand_cmd(l2, var_dict, ns, expanded, False)
    if not found_match:
        sys.stderr.write("ERROR: Unable to find a valid match for "
                         "'{}'.\n\n".format(var_name))
        sys.stderr.write("Use '--error-string ERROR_STRING' to "
                         "specify a matching string.\n")
        sys.exit(1)


def expand_range(option, var_name, line, var_dict, ns, expanded,
                 should_succeed):
    min_value, max_value = var_dict[var_name[1:]]
    if min_value:
        l2 = line.replace(var_name, str(min_value), 1)
        expand_cmd(l2, var_dict, ns, expanded, should_succeed)
        if should_succeed:
            l2 = line.replace(var_name, str(min_value - 1), 1)
            expand_cmd(l2, var_dict, ns, expanded, False)
    if max_value:
        l2 = line.replace(var_name, str(max_value), 1)
        expand_cmd(l2, var_dict, ns, expanded, should_succeed)
        if should_succeed and option not in expanded:
            l2 = line.replace(var_name, str(max_value + 1), 1)
            expand_cmd(l2, var_dict, ns, expanded, False)


def expand_enum(option, var_name, line, var_dict, ns, expanded,
                should_succeed):
    for enum in var_dict[var_name[1:]]:
        l2 = line.replace(var_name, shell_quote(enum), 1)
        expand_cmd(l2, var_dict, ns, expanded, should_succeed)
        if option in expanded:
           break
    if should_succeed and option not in expanded:
        l2 = line.replace(var_name,
                          shell_quote("non-existent-enum"), 1)
        expand_cmd(l2, var_dict, ns, expanded, False)


def expand_optional_param(line, var_dict, ns, expanded,
                          should_succeed):
    match = re.search(r'\[\s*(.+?)\s*\]', line)
    if match:
        match2 = re.search(r'(-{1,2}\w+)=(\$\w+)', match.group(1))
        if match2:
            expanded.append("<optional>" + match2.group(1).strip())
        # Validate command with the argument set
        l2 = line.replace(match.group(0), match.group(1), 1)
        expand_cmd(l2, var_dict, ns, expanded, should_succeed)
        # Validate command without the argument set
        l2 = line.replace(match.group(0), "", 1)
        expand_cmd(l2, var_dict, ns, expanded, should_succeed)
    return match


def expand_required_param(line, var_dict, ns, expanded,
                          should_succeed):
    match = re.search(r'(\s+)(-{1,2}\w+)=(\$\w+)', line)
    if match:
        # Replace the equals sign by a space, as it will work for both
        # short and GNU long options
        l2 = line.replace(match.group(0), ' ' + match.group(2) + ' ' +
                          match.group(3), 1)
        var_name = match.group(3)
        if var_dict.is_regex(var_name[1:]):
            expand_regex(match.group(2), var_name, l2, var_dict, ns,
                         expanded, should_succeed)
        elif var_dict.is_range(var_name[1:]):
            expand_range(match.group(2), var_name, l2, var_dict, ns,
                         expanded, should_succeed)
        elif var_dict.is_enum(var_name[1:]):
            expand_enum(match.group(2), var_name, l2, var_dict, ns,
                        expanded, should_succeed)
        else:
            sys.stderr.write("Error: variable '{}' is undefined\n"
                             .format(var_name))
            sys.exit(1)
        if match.group(2) not in expanded:
            expanded.append(match.group(2))
            # FIXME This is wrong because e.g. on '--hour --minute 60',
            # the --hour parameter is not being tested as if no arg was
            # given, but with a '--minute' arg.
            #l2 = line.replace('=' + match.group(3), "", 1)
            #expand_cmd(l2, var_dict, ns, expanded, False)
        if "<optional>" + match.group(2) not in expanded:
            l2 = line.replace(match.group(), "", 1)
            expand_cmd(l2, var_dict, ns, expanded, False)
    return match


def expand_cmd(line, var_dict, ns, expanded, should_succeed):
    if expand_optional_param(line, var_dict, ns, expanded,
                             should_succeed):
        pass
    elif expand_required_param(line, var_dict, ns, expanded,
                               should_succeed):
        pass
    else:
        run_command(line, ns, should_succeed)


def invalid_variable_declaration_err(line):
    sys.stderr.write("Invalid syntax in variable declaration: " +
                     line + "\n")
    sys.exit(1)


def parse_line(line, cmd_lines, var_dict, regex_cre, range_cre,
               enum_cre):
    if line.startswith('regex'):
        match = regex_cre.match(line)
        if not match:
            invalid_variable_declaration_err(line)
        regex = match.group(2)
        if not regex.startswith("^"):
            regex = "^" + regex
        if not regex.endswith("$"):
            regex = regex + "$"
        var_dict[match.group(1)] = regex
    elif line.startswith('range'):
        match = range_cre.match(line)
        if not match or (not match.group(2) and not match.group(3)):
            invalid_variable_declaration_err(line)
        lower_limit = int(match.group(2)) if match.group(2) else None
        upper_limit = int(match.group(3)) if match.group(3) else None
        var_dict[match.group(1)] = lower_limit, upper_limit
    elif line.startswith('enum'):
        match = enum_cre.match(line)
        if not match:
            invalid_variable_declaration_err(line)
        var_dict[match.group(1)] = [s.strip()
                                    for s in match.group(2).split(',')]
    elif line.startswith('#') or not line.strip():
        pass
    else:
        cmd_lines.append(line)


def parse_files(files):
    cmd_lines = []
    var_dict = VarDict()
    regex_cre = re.compile(r"regex\s+(\w+)\s*=\s*(.+?)\s*$")
    range_cre = re.compile(r"range\s+(\w+)\s*=\s*(\d*)\s*\.\.\s*(\d*)")
    enum_cre = re.compile(r"enum\s+(\w+)\s*=\s*(.+)")
    for filepath in files:
        with open(filepath, 'r') as f:
            for line in f.read().splitlines():
                parse_line(line, cmd_lines, var_dict,
                           regex_cre, range_cre, enum_cre)
    return cmd_lines, var_dict


def run_input_validation_tester(cmd_lines, var_dict, namespace):
    for cmd_line in cmd_lines:
        expand_cmd(cmd_line, var_dict, namespace, [], True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--error-string', action="append",
                        default=[], help="error string to match")
    parser.add_argument('files', nargs='+', help="list of spec files")
    parser.add_argument('-t', '--test-string', action="append",
                        help="extra test strings")
    parser.add_argument('--quick-check', action='store_true',
                        help="Only try the invalid strings given in "
                             "the command line")
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--quiet', action='store_true',
                       help="don't show any output")
    group.add_argument('--verbose', action='store_true',
                       help="activate verbose output")
    namespace = parser.parse_args()

    if not len(namespace.files):
        parser.error("wrong number of arguments")

    if namespace.test_string:
        if not namespace.quick_check:
            namespace.test_string += get_test_strings()
    else:
        if namespace.quick_check:
            parser.error("'--quick-check' requires '--test-string'")
        else:
            namespace.test_string = get_test_strings()

    cmd_lines, var_dict = parse_files(namespace.files)

    if namespace.verbose:
        print ("Variables:")
        pprint.pprint(var_dict)
        print ("Commands:")
        pprint.pprint(cmd_lines)

    run_input_validation_tester(cmd_lines, var_dict, namespace)


if __name__ == "__main__":
    main()
